export const SET_DATA = 'SET_DATA';

export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';

export const SET_MESSAGES_FOR_ACTIVE_CHAT = 'SET_MESSAGES_FOR_ACTIVE_CHAT';

export const SET_CHATS = 'SET_CHATS';

export const NEW_MESSAGE = 'NEW_MESSAGE';

export const ADD_ALERTED_CHAT = 'ADD_ALERTED_CHAT';

export const REMOVE_ALERTED_CHAT = 'REMOVE_ALERTED_CHAT';

export const ADD_DRAFT_MESSAGE = 'ADD_DRAFT_MESSAGE'

export const SHOW_LOADER = 'SHOW_LOADER'

export const SET_I_DATA = 'SET_I_DATA'

export const UNSET_ACTIVE_CHAT = 'UNSET_ACTIVE_CHAT'

export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'

export const READ_MESSAGE = 'READ_MESSAGE'